### ISSUE TITLE
Interactive session logging

### ISSUE THREAD

**Issue by bczernecki** [atorus-research/timber#1]
First of all thank you for developing **timber** which seems to be the most promising tool for our purposes.
However, I miss one crucial functionality that would allow to create a log based on user input provided in an interactive session, instead of a pre-existing .R file. 
I think such a feature would make the package a complete product. Do you plan to add such an option to the timber?

Thanks!
Bartek

**Comment by kodesiba** [comment]
Bartek,

Thank you so much for checking out `timber`, it's always cool to hear people are using it!

While interactive sessions are difficult in R it is something we would consider looking in to implementing.  I wanted to get some clarification on the request before going forward with looking into the implementation.  Let me know if this sounds wrong but it sounds as though you would like to start a new session, run a log setup function to get the framework in place, run some code in the console that might bring in new libraries, create errors and warnings, etc., and then be able to capture what happened in the `timber` log format and write that file out to somewhere.  If this sounds right I can look more into it and talk with the other developers, if I'm misunderstanding please let me know what you were thinking the process would be and we can see what we can do.

- Nathan Kosiba

**Comment by bczernecki** [comment]
Hi @kodesiba ,

Yes, so I was thinking about an approach that you have described above. 
Basically, we want to track the behaviour of an end-user and capture all instructions that are run in "live" RStudio session after loading our package. We want to log `print/cat`, `message` and `error` statements that will be saved in a log file and simultanously it should be visible on the R console. I hope this is a bit more clear now :)

Thanks,
Bartek

**Comment by mstackhouse** [comment]
@bczernecki question for you. What you're suggesting sounds similar to what you can achieve with the function [`sync()`](https://stat.ethz.ch/R-manual/R-devel/library/base/html/sink.html) within base R. Look at the option `split`:

<html>
<body>


split | logical: if TRUE, output will be sent to the new sink and to the current output stream, like the Unix program tee.
-- | --



</body>
</html>

My thought is that you could throw this in the package `.onLoad()` function. You'd want `.onUnload()` to clean up as well. Read more [here](https://rdrr.io/r/base/ns-hooks.html). 

All this said - this is probably out of scope of {timber}. This package is targeted at audit trails associated with batch runs, which is why there hasn't been much focus on interactive runs.

**Comment by bczernecki** [comment]
Thanks @mstackhouse for the explanation. Yes, I am using `sink` with `.onLoad/.onAttach` statements, so basically that covers what I need. Thx!
